name: beacon
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_blue_plus: ^1.4.0
  permission_handler: ^11.0.0
  provider: ^6.1.5+1
  google_fonts: ^6.3.3
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  flutter_tts: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
